/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusIndexRouteImport } from './routes/status/index'
import { Route as AcademyIndexRouteImport } from './routes/academy/index'
import { Route as AppStrategiesIndexRouteImport } from './routes/app/strategies/index'
import { Route as AppSignalsIndexRouteImport } from './routes/app/signals/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppHealthIndexRouteImport } from './routes/app/health/index'
import { Route as AppBacktestsIndexRouteImport } from './routes/app/backtests/index'
import { Route as AppSignalsSignalIdRouteImport } from './routes/app/signals/$signalId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusIndexRoute = StatusIndexRouteImport.update({
  id: '/status/',
  path: '/status/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStrategiesIndexRoute = AppStrategiesIndexRouteImport.update({
  id: '/strategies/',
  path: '/strategies/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSignalsIndexRoute = AppSignalsIndexRouteImport.update({
  id: '/signals/',
  path: '/signals/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHealthIndexRoute = AppHealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBacktestsIndexRoute = AppBacktestsIndexRouteImport.update({
  id: '/backtests/',
  path: '/backtests/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSignalsSignalIdRoute = AppSignalsSignalIdRouteImport.update({
  id: '/signals/$signalId',
  path: '/signals/$signalId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/academy/': typeof AcademyIndexRoute
  '/status/': typeof StatusIndexRoute
  '/app/signals/$signalId': typeof AppSignalsSignalIdRoute
  '/app/backtests/': typeof AppBacktestsIndexRoute
  '/app/health/': typeof AppHealthIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/signals/': typeof AppSignalsIndexRoute
  '/app/strategies/': typeof AppStrategiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/academy': typeof AcademyIndexRoute
  '/status': typeof StatusIndexRoute
  '/app/signals/$signalId': typeof AppSignalsSignalIdRoute
  '/app/backtests': typeof AppBacktestsIndexRoute
  '/app/health': typeof AppHealthIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/signals': typeof AppSignalsIndexRoute
  '/app/strategies': typeof AppStrategiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/academy/': typeof AcademyIndexRoute
  '/status/': typeof StatusIndexRoute
  '/app/signals/$signalId': typeof AppSignalsSignalIdRoute
  '/app/backtests/': typeof AppBacktestsIndexRoute
  '/app/health/': typeof AppHealthIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/signals/': typeof AppSignalsIndexRoute
  '/app/strategies/': typeof AppStrategiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/academy/'
    | '/status/'
    | '/app/signals/$signalId'
    | '/app/backtests/'
    | '/app/health/'
    | '/app/settings/'
    | '/app/signals/'
    | '/app/strategies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/academy'
    | '/status'
    | '/app/signals/$signalId'
    | '/app/backtests'
    | '/app/health'
    | '/app/settings'
    | '/app/signals'
    | '/app/strategies'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/academy/'
    | '/status/'
    | '/app/signals/$signalId'
    | '/app/backtests/'
    | '/app/health/'
    | '/app/settings/'
    | '/app/signals/'
    | '/app/strategies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AcademyIndexRoute: typeof AcademyIndexRoute
  StatusIndexRoute: typeof StatusIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/': {
      id: '/status/'
      path: '/status'
      fullPath: '/status/'
      preLoaderRoute: typeof StatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/strategies/': {
      id: '/app/strategies/'
      path: '/strategies'
      fullPath: '/app/strategies/'
      preLoaderRoute: typeof AppStrategiesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/signals/': {
      id: '/app/signals/'
      path: '/signals'
      fullPath: '/app/signals/'
      preLoaderRoute: typeof AppSignalsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/health/': {
      id: '/app/health/'
      path: '/health'
      fullPath: '/app/health/'
      preLoaderRoute: typeof AppHealthIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/backtests/': {
      id: '/app/backtests/'
      path: '/backtests'
      fullPath: '/app/backtests/'
      preLoaderRoute: typeof AppBacktestsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/signals/$signalId': {
      id: '/app/signals/$signalId'
      path: '/signals/$signalId'
      fullPath: '/app/signals/$signalId'
      preLoaderRoute: typeof AppSignalsSignalIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppSignalsSignalIdRoute: typeof AppSignalsSignalIdRoute
  AppBacktestsIndexRoute: typeof AppBacktestsIndexRoute
  AppHealthIndexRoute: typeof AppHealthIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSignalsIndexRoute: typeof AppSignalsIndexRoute
  AppStrategiesIndexRoute: typeof AppStrategiesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSignalsSignalIdRoute: AppSignalsSignalIdRoute,
  AppBacktestsIndexRoute: AppBacktestsIndexRoute,
  AppHealthIndexRoute: AppHealthIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSignalsIndexRoute: AppSignalsIndexRoute,
  AppStrategiesIndexRoute: AppStrategiesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AcademyIndexRoute: AcademyIndexRoute,
  StatusIndexRoute: StatusIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
